name: ReadCraig
favicon: null
layout_spectrum: 0.3379409392364323
typography_spectrum: 0.10379635938443244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.43178622680716217
  lightness: 0.9850668171420693
  saturation: 0.7802451064344496
  rhythmicContrast: 0.05085258022882044
purpose: []
